pipeline:
  name: pGitX1
  identifier: pGitX1
  projectIdentifier: p1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: swithoutArtifact
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  variables:
                    - name: v1
                      type: String
                      value: <+input>
                    - name: v2
                      type: String
                      value: <+input>
                  manifests:
                    - manifest:
                        identifier: mm
                        type: K8sManifest
                        spec:
                          store:
                            type: Github
                            spec:
                              branch: <+input>
          environment:
            environmentRef: e1
            deployToAll: false
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  connectorRef: TathAccount
  storeType: REMOTE
  filePath: .harness/p1.yaml
